# WhatATheme
markdown: kramdown

# URL of the Site
url: https://yi-sang.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:  

# Title of the Site
title: Dream Developer
# Description of the Site
description: modern classic
# URL of Image of the Site
site-image: https://user-images.githubusercontent.com/80687913/134811865-3a21f8a7-fb21-4d12-bc77-76d4de778c5f.jpg
  # /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://user-images.githubusercontent.com/80687913/134811865-3a21f8a7-fb21-4d12-bc77-76d4de778c5f.jpg
  # https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sanghyle@icloud.com 
# facebook_username: 
# twitter_username: 
instagram_username: yi___sang
# linkedin_username: 
github_username:  yi-sang
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: /yi-sang

# Name of the Author
author-name: Hyle
# URL for the Image of the Author
author-image: https://user-images.githubusercontent.com/80687913/132556599-a5cb5a9a-bd2e-47c0-8652-f9117bf9775f.jpeg
# 60 Words About the Author
author-about: Dream of becoming an iOS developer through communication.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
